pos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls,name="admin-site"),
    path('', include('posApp.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posApp/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('redirect-admin', RedirectView.as_view(url="/admin"),name="redirect-admin"),
    path('', views.home, name="home-page"),
    path('login', views.CustomLoginView.as_view(), name="login"),
    path('userlogin', views.login_user, name="login-user"),
    path('logout', views.logoutuser, name="logout"),
    path('category', views.category, name="category-page"),
    path('cambiar_sucursal/', views.cambiar_sucursal, name='cambiar-sucursal'),
    path('manage_category', views.manage_category, name="manage_category-page"),
    path('save_category', views.save_category, name="save-category-page"),
    path('delete_category', views.delete_category, name="delete-category"),
    path('products', views.products, name="product-page"),
    path('clientes', views.clients, name="client-page"),
    path('manage_products', views.manage_products, name="manage_products-page"),
    path('manage_clients', views.manage_clients, name="manage_clients-page"),
    path('save_product', views.save_product, name="save-product-page"),
    path('save_client', views.save_client, name="save-client-page"),
    path('delete_product', views.delete_product, name="delete-product"),
    path('pos', views.pos, name="pos-page"),
    path('checkout-modal', views.checkout_modal, name="checkout-modal"),
    path('save-pos', views.save_pos, name="save-pos"),
    path('sales', views.salesList, name="sales-page"),
    path('receipt', views.receipt, name="receipt-modal"),
    path('delete_sale', views.delete_sale, name="delete-sale"),
    path('create-seller/', views.SellerUserCreateView.as_view(), name='create_seller_user'),
    path('delete_cliente/', views.delete_cliente, name='delete_cliente'),
    path('plans/', views.plans, name='plans-page'),
    path('editar-plan/<int:pk>/', views.editar_plan, name='editar-plan'),
    path('delete_plan/', views.delete_plan, name='delete-plan'),
    path('clientes/<int:cliente_id>/mensualidades/', views.cliente_mensualidades, name='cliente_mensualidades'),
    path('salida/add/', views.add_salida, name='add_salida'),
    path('clientes/<int:cliente_id>/mensualidades/pagar/', views.pagar_primera_mensualidad, name='pagar_primera_mensualidad'),
    path('seleccionar-mensualidades/<int:cliente_id>/', views.seleccionar_mensualidades, name='seleccionar-mensualidades'),
    path('generar-mensualidades/<int:cliente_id>/', views.generar_mensualidades, name='generar-mensualidades'),
    path('plan-inscripcion/create/', views.create_plan_inscripcion, name='create_plan_inscripcion'),
    path('create-sucursal/', views.create_sucursal, name='create_sucursal'),
    path('export_sales_to_excel/', views.export_sales_to_excel, name='export_sales_to_excel'),
    path('api/clientes/search/', views.buscar_clientes, name='buscar_clientes'),
    path('reportes/mensual/', views.dashboard_report, name='monthly_report'),
    path('proxy/image/<str:image_url_b64>/', views.image_proxy, name='image_proxy'),
]

posApp/models.py
from datetime import datetime
from unicodedata import category
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

# class Employees(models.Model):
#     code = models.CharField(max_length=100,blank=True) 
#     firstname = models.TextField() 
#     middlename = models.TextField(blank=True,null= True) 
#     lastname = models.TextField() 
#     gender = models.TextField(blank=True,null= True) 
#     dob = models.DateField(blank=True,null= True) 
#     contact = models.TextField() 
#     address = models.TextField() 
#     email = models.TextField() 
#     department_id = models.ForeignKey(Department, on_delete=models.CASCADE) 
#     position_id = models.ForeignKey(Position, on_delete=models.CASCADE) 
#     date_hired = models.DateField() 
#     salary = models.FloatField(default=0) 
#     status = models.IntegerField() 
#     date_added = models.DateTimeField(default=timezone.now) 
#     date_updated = models.DateTimeField(auto_now=True) 

    # def __str__(self):
    #     return self.firstname + ' ' +self.middlename + ' '+self.lastname + ' '

class Sucursal(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200, blank=True, null=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_seller = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    sucursales = models.ManyToManyField(Sucursal, related_name='managers', blank=True)
    is_modelo = models.BooleanField(default=False)  # Nuevo campo para Acuática Modelo
    is_modelo_manager = models.BooleanField(default=False)  # Nuevo campo para Acuática Modelo Manager

    def __str__(self):
        return self.user.username

class Genero(models.Model):
    genero = models.CharField(max_length=20)

    def __str__(self):
        return str(self.genero)


class PlanInscripcion(models.Model):
    nombre = models.CharField(max_length=100, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    duracion = models.IntegerField(default=30)  # Duración en días
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.nombre




class Levels(models.Model):
    level = models.CharField(max_length=100, blank=True, null=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return str(self.level)
    

class Clientes(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICE = (
        (MALE, 'Hombre'),
        (FEMALE, 'Mujer')
    )

    SINGLE = 'S'
    MARRIED = 'M'
    DIVORCE = 'D'
    FREE = 'F'
    CIVIL_CHOICE = (
        (SINGLE, 'Soltero'),
        (MARRIED, 'Casado'),
        (DIVORCE, 'Divorsiado'),
        (FREE, 'Union libre')
    )

    FACEBOOK = 'F'
    RECOMANDATION = 'R'
    TRANSIT = 'T'
    OTHER = 'F'
    FIND_CHOICES = (
        (FACEBOOK, 'Facebook'),
        (RECOMANDATION, 'Recomendacion'),
        (TRANSIT, 'Transito'),
        (OTHER, 'Otro')
    )

    nombre = models.CharField(max_length=50)
    #picture = models.ImageField(verbose_name='foto', null=True, blank=True)
    #image_source = models.TextField()
    apellido_materno = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    fecha_nacimiento = models.CharField(max_length=100,blank=True, null=True)
    genero = models.ForeignKey(Genero, on_delete=models.DO_NOTHING, null=True, blank=True)
    direccion = models.CharField(max_length=200)
    suburbio = models.CharField(max_length=200)
    codigo_postal = models.CharField(max_length=10)
    celular = models.CharField(max_length=12)
    email = models.EmailField(blank=True, null=True)
    #estado_civil = models.CharField(max_length=10, choices=CIVIL_CHOICE)
    
    sangre = models.CharField(max_length=50)
    contacto_emergencia = models.CharField(max_length=200)
    emergency_phone = models.CharField(max_length=20)
    pay_day = models.CharField(max_length=200)
    condicion_medica = models.TextField()
    horario = models.TextField()
    nivel = models.ForeignKey(Levels, on_delete=models.DO_NOTHING, null=True, blank=True)
    status = models.IntegerField(default=1)
    plan_inscripcion = models.ForeignKey(PlanInscripcion, on_delete=models.SET_NULL, null=True, blank=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    estado_mensualidad = models.CharField(max_length=20, default='Sin mensualidades') 

    def __str__(self):
        return str(self.nombre)
    
class Mensualidad(models.Model):
    cliente = models.ForeignKey(Clientes, on_delete=models.CASCADE, blank=True, null=True)
    fecha_vencimiento = models.DateField(blank=True, null=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pagado = models.BooleanField(default=False, blank=True, null=True)
    fecha_pago = models.DateField(null=True, blank=True)
    plan_inscripcion = models.ForeignKey(PlanInscripcion, on_delete=models.CASCADE, blank=True, null=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return f"{self.cliente.nombre} - {self.fecha_vencimiento} - {'Pagado' if self.pagado else 'Pendiente'}"

class Category(models.Model):
    name = models.TextField()
    description = models.TextField()
    status = models.IntegerField(default=1) 
    date_added = models.DateTimeField(default=timezone.now) 
    date_updated = models.DateTimeField(auto_now=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True) 

    def __str__(self):
        return self.name

class Products(models.Model):
    code = models.CharField(max_length=100)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.TextField()
    description = models.TextField()
    price = models.FloatField(default=0)
    status = models.IntegerField(default=1)
    date_added = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    cantidad_disponible = models.IntegerField(default=0)  # Nueva columna para inventario

    def __str__(self):
        return self.code + " - " + self.name

    
class FormaPago(models.Model):
    tipo = models.CharField(max_length=100)

    def __str__(self):
        return self.tipo
    

class Sales(models.Model):
    code = models.CharField(max_length=100)
    sub_total = models.FloatField(default=0)
    grand_total = models.FloatField(default=0)
    tax_amount = models.FloatField(default=0)
    tax = models.FloatField(default=0)
    tendered_amount = models.FloatField(default=0)
    tendered_amount_card = models.FloatField(default=0)
    amount_change = models.FloatField(default=0)
    date_added = models.DateTimeField(default=timezone.now, db_index=True)
    date_updated = models.DateTimeField(auto_now=True)
    client = models.ForeignKey(Clientes, on_delete=models.PROTECT, db_index=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    tipoPago = models.ForeignKey(FormaPago, on_delete=models.PROTECT, db_index=True)
    comentario = models.CharField(max_length=700, null=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True, db_index=True)

    def __str__(self):
        return self.code

    class Meta:
        indexes = [
            models.Index(fields=['sucursal', 'date_added'], name='sales_sucursal_date_idx'),
        ]
class salesItems(models.Model):
    sale_id = models.ForeignKey(Sales,on_delete=models.CASCADE)
    product_id = models.ForeignKey(Products,on_delete=models.CASCADE, blank=True, null=True)
    product_name = models.CharField(max_length=255, blank=True, null=True)  # Nuevo campo
    price = models.FloatField(default=0)
    qty = models.FloatField(default=0)
    total = models.FloatField(default=0)
    client = models.ForeignKey(Clientes, on_delete=models.CASCADE)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    

class Salida(models.Model):
    concepto = models.CharField(max_length=200, blank=True, null=True)
    monto = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    fecha = models.DateField(blank=True, null=True)
    comentario = models.TextField(blank=True, null=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return f"{self.concepto} - {self.monto} - {self.fecha}"

posApp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from posApp.models import Sucursal, PlanInscripcion, Mensualidad, Salida

class SellerUserCreationForm(UserCreationForm):
    sucursal = forms.ModelChoiceField(queryset=Sucursal.objects.all(), required=True)
    
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'sucursal')

    def __init__(self, *args, **kwargs):
        super(SellerUserCreationForm, self).__init__(*args, **kwargs)


class PlanInscripcionForm(forms.ModelForm):
    class Meta:
        model = PlanInscripcion
        fields = ['nombre', 'descripcion', 'precio', 'duracion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'required': True}),
            'precio': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01', 'required': True}),
            'duracion': forms.NumberInput(attrs={'class': 'form-control', 'required': True, 'min': '1'}),  # Campo duración
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nombre'].required = True
        self.fields['descripcion'].required = True
        self.fields['precio'].required = True
        self.fields['duracion'].required = True  # Aseguramos que la duración también sea requerida


class MensualidadForm(forms.ModelForm):
    tendered_amount_cash = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        required=False, 
        initial=0, 
        widget=forms.NumberInput(attrs={'style': 'display:none;'}),
        label=''
    )
    tendered_amount_card = forms.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        required=False, 
        initial=0, 
        widget=forms.NumberInput(attrs={'style': 'display:none;'}),
        label=''
    )

    class Meta:
        model = Mensualidad
        fields = ['fecha_vencimiento', 'plan_inscripcion', 'monto', 'tendered_amount_cash', 'tendered_amount_card']
        widgets = {
            'fecha_vencimiento': forms.DateInput(attrs={'type': 'date'}),
            'plan_inscripcion': forms.Select(attrs={'class': 'form-select'}),
            'monto': forms.NumberInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),  # Make monto field read-only
        }

class SalidaForm(forms.ModelForm):
    class Meta:
        model = Salida
        fields = ['concepto', 'monto', 'fecha', 'comentario']
        widgets = {
            'fecha': forms.DateInput(attrs={'type': 'date'}),
            'comentario': forms.Textarea(attrs={'rows': 4}),
        }
        labels = {
            'concepto': 'Concepto',
            'monto': 'Monto',
            'fecha': 'Fecha',
            'comentario': 'Comentario (opcional)',
        }
        
class SucursalForm(forms.ModelForm):
    class Meta:
        model = Sucursal
        fields = ['nombre', 'direccion', 'telefono']

posApp/templates/posApp/cambiar_sucursal.html
{% extends "posApp/base.html" %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <form method="POST">
        {% csrf_token %}
        <label for="sucursal">Seleccionar Sucursal:</label>
        <select name="sucursal" id="sucursal">
            {% for sucursal in sucursales %}
            <option value="{{ sucursal.id }}">{{ sucursal.nombre }}</option>
            {% endfor %}
        </select>
        <button type="submit">Cambiar</button>
    </form>
</div>


<style>
    form {
    background-color: #fff;
    padding: 20px;
    margin: 50px auto;
    width: 100%;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
}

form label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
}

form select,
form button {
    width: 100%;
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

form button {
    background-color: #007bff;
    color: #fff;
    border: none;
    cursor: pointer;
}

form button:hover {
    background-color: #0056b3;
}
</style>

{% endblock %}

posApp/templates/posApp/checkout.html
{% load humanize %}
<div class="container-fluid">
    <form action="" id="checkout-form">
        <div class="form-group mb-3">
            <label for="payable_amount" class="control-label">Cantidad a pagar</label>
            <input type="text" id="payable_amount" class="form-control form-control-lg rounded-0 text-end" value="{{ grand_total|intcomma }}" required disabled>
        </div>
        <div class="form-group mb-3">
            <label for="tendered_amount" class="control-label">Cantidad recibida efectivo</label>
            <input type="number" step="any" id="tendered_amount" class="form-control form-control-lg rounded-0 text-end" value="0" required>
        </div>

        <div class="form-group mb-3">
            <label for="tendered_amount" class="control-label">Cantidad recibida tarjeta</label>
            <input type="number" step="any" id="tendered_amount_card" class="form-control form-control-lg rounded-0 text-end" value="0" required>
        </div>

        <div class="form-group mb-3">
            <label for="payment_change" class="control-label">Cambio</label>
            <input type="text" id="payment_change" class="form-control form-control-lg rounded-0 text-end" value="{{ 0|intcomma }}" required disabled>
        </div>
        
       

    </form>
</div>
<script>
    $(function() {
        $('#tendered_amount, #tendered_amount_card').on('input keypress keyup keydown', function() {
        var tendered_amount = parseFloat($('#tendered_amount').val().replace(/,/gi, ''));
        var tendered_amount_card = parseFloat($('#tendered_amount_card').val().replace(/,/gi, ''));
        var payable = parseFloat($('#payable_amount').val().replace(/,/gi, ''));
        var change = (tendered_amount || 0) + (tendered_amount_card || 0) - payable;

        $('[name="tendered_amount"]').val(tendered_amount);
        $('[name="tendered_amount_card"]').val(tendered_amount_card);
        $('#payment_change').val(parseFloat(change).toLocaleString('en-US'));
        $('[name="amount_change"]').val(change);
    });
        $('#checkout-form').submit(function(e) {
            e.preventDefault();
            if ($('[name="amount_change"]').val() < 0) {
                alert("Tendered Amount is lower that Payable Amount")
                return false;
            }
            $('#pos-form').submit()
        })
    })
</script>

posApp/templates/posApp/create_plan_inscripcion.html
{% extends "posApp/base.html" %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Agregar Plan de Inscripción</h4>
        </div>
        <div class="card-body">
            <form method="post" class="form-container">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-end">
                    <button type="submit" class="btn btn-primary bg-gradient rounded-0">Guardar Plan</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

posApp/templates/posApp/editar_plan.html
{% extends "posApp/base.html" %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Editar Plan de Inscripción</h4>
        </div>
        <div class="card-body">
            <form method="post" class="form-container">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="text-end">
                    <button type="submit" class="btn btn-primary bg-gradient rounded-0">Actualizar Plan</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

posApp/templates/posApp/multiples_mensualidades.html
{% extends "posApp/base.html" %}

{% block pageContent %}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12">
    <div class="mdc-card py-2">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title mb-0">Seleccionar Múltiples Mensualidades</h4>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'generar-mensualidades' cliente.id %}">
                {% csrf_token %}
                
                <!-- Selección del plan de inscripción -->
                <div class="form-group">
                    <label for="id_plan_inscripcion">Plan Inscripción:</label>
                    <select name="plan_inscripcion" id="id_plan_inscripcion" class="form-control" required>
                        <option value="">Selecciona un plan</option>
                        {% for plan in planes_inscripcion %}
                        <option value="{{ plan.id }}">{{ plan.nombre }} - ${{ plan.precio }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Selección de meses -->
                <div class="form-group">
                    <label for="meses">Selecciona los meses</label>
                    <div class="row">
                        <div class="col-md-6">
                            {% for mes in meses_disponibles|slice:":6" %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="meses[]" value="{{ mes }}" id="mes_{{ mes }}">
                                <label class="form-check-label" for="mes_{{ mes }}">
                                    {{ mes }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col-md-6">
                            {% for mes in meses_disponibles|slice:"6:" %}
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="meses[]" value="{{ mes }}" id="mes_{{ mes }}">
                                <label class="form-check-label" for="mes_{{ mes }}">
                                    {{ mes }}
                                </label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!-- Día de cobro -->
                <div class="form-group">
                    <label for="dia">Día de Cobro</label>
                    <input type="number" name="dia" id="dia" class="form-control" placeholder="15" required>
                </div>

                <!-- Monto total -->
                <div class="form-group">
                    <label for="monto">Monto Total:</label>
                    <input type="text" id="monto" class="form-control" readonly>
                </div>

                <!-- Tipo de pago -->
                <div class="form-group">
                    <label for="forma_pago">Forma de Pago:</label>
                    <select name="forma_pago" id="forma_pago" class="form-control">
                        {% for pago in formas_pago %}
                        <option value="{{ pago.id }}">{{ pago.tipo }}</option>
                        {% endfor %}
                    </select>
                </div>

                <!-- Pago en efectivo -->
                <div class="form-group" id="cash_group">
                    <label for="tendered_amount_cash">Cantidad Pagada en Efectivo</label>
                    <input type="number" step="0.01" name="tendered_amount_cash" id="tendered_amount_cash" class="form-control" value="0">
                </div>

                <!-- Pago con tarjeta -->
                <div class="form-group" id="card_group">
                    <label for="tendered_amount_card">Cantidad Pagada con Tarjeta</label>
                    <input type="number" step="0.01" name="tendered_amount_card" id="tendered_amount_card" class="form-control" value="0">
                </div>

                <!-- Cambio -->
                <div class="form-group">
                    <label for="id_cambio">Cambio:</label>
                    <input type="text" id="id_cambio" class="form-control" readonly>
                </div>

                <div class="text-end">
                    <button type="submit" class="btn btn-primary bg-gradient rounded-0">Generar Mensualidades</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const planInscripcionSelect = document.getElementById('id_plan_inscripcion');
        const mesesCheckboxes = document.querySelectorAll('input[name="meses[]"]');
        const montoInput = document.getElementById('monto');
        const formaPagoSelect = document.getElementById('forma_pago');
        const cashGroup = document.getElementById('cash_group');
        const cardGroup = document.getElementById('card_group');
        const cashInput = document.getElementById('tendered_amount_cash');
        const cardInput = document.getElementById('tendered_amount_card');
        const cambioInput = document.getElementById('id_cambio');
        let precioPlan = 0;

        // Ocultar o mostrar los campos de efectivo y tarjeta según la forma de pago seleccionada
        function actualizarFormaPago() {
            const selectedPaymentMethod = formaPagoSelect.options[formaPagoSelect.selectedIndex].text.toLowerCase();
            if (selectedPaymentMethod.includes('efectivo') && selectedPaymentMethod.includes('tarjeta')) {
                cashGroup.style.display = '';
                cardGroup.style.display = '';
            } else if (selectedPaymentMethod.includes('efectivo')) {
                cashGroup.style.display = '';
                cardGroup.style.display = 'none';
            } else if (selectedPaymentMethod.includes('banco')) {
                cashGroup.style.display = 'none';
                cardGroup.style.display = '';
            } else {
                cashGroup.style.display = 'none';
                cardGroup.style.display = 'none';
            }
        }

        // Función para actualizar el monto total
        function actualizarMonto() {
            let mesesSeleccionados = 0;
            mesesCheckboxes.forEach((checkbox) => {
                if (checkbox.checked) {
                    mesesSeleccionados++;
                }
            });
            const montoTotal = mesesSeleccionados * precioPlan;
            montoInput.value = montoTotal.toFixed(2);
            actualizarCambio();
        }

        // Función para calcular y mostrar el cambio
        function actualizarCambio() {
            const montoTotal = parseFloat(montoInput.value) || 0;
            const pagadoEnEfectivo = parseFloat(cashInput.value) || 0;
            const pagadoConTarjeta = parseFloat(cardInput.value) || 0;
            const totalPagado = pagadoEnEfectivo + pagadoConTarjeta;
            const cambio = totalPagado - montoTotal;

            cambioInput.value = cambio >= 0 ? cambio.toFixed(2) : '0.00';
        }
        const planInscripcionOptions = {
            {% for plan in planes_inscripcion %}
            '{{ plan.id }}': {
                'precio': {{ plan.precio|floatformat:2 }}
            },
            {% endfor %}
        };

        // Evento para actualizar el precio según el plan seleccionado
        planInscripcionSelect.addEventListener('change', function() {
            const selectedPlanId = this.value;
            if (planInscripcionOptions.hasOwnProperty(selectedPlanId)) {
                precioPlan = planInscripcionOptions[selectedPlanId].precio;
            } else {
                precioPlan = 0;
            }
            actualizarMonto();
        });

        // Evento para actualizar el monto cuando se seleccionan/desseleccionan meses
        mesesCheckboxes.forEach((checkbox) => {
            checkbox.addEventListener('change', actualizarMonto);
        });

        // Actualizar campos de pago cuando se cambia la forma de pago
        formaPagoSelect.addEventListener('change', actualizarFormaPago);

        // Escuchar cambios en los inputs de efectivo y tarjeta para recalcular el cambio
        cashInput.addEventListener('input', actualizarCambio);
        cardInput.addEventListener('input', actualizarCambio);

        // Inicializar los campos al cargar la página
        actualizarFormaPago();
    });
</script>
{% endblock %}